print("welcome to the tip calculato. ")
total_bill = int(input("what was the total bill? "))
print(total_bill)
percentage_tip = int(input("what percentge tip would you like to give? "))
print(percentage_tip)
no_of_people = int(input("how many people to split the bill? "))
print(no_of_people)
cost_per_person = (((percentage_tip/100)+1)*total_bill)/no_of_people
rounded_cost = round(cost_per_person, 2)
print(f"each person should pay{rounded_cost}")
